version: '3.8'

services:
  pokedex-app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - DJANGO_SETTINGS_MODULE=pokedex_project.settings
    volumes:
      - ./staticfiles:/app/staticfiles
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/pokemon/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

