name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run Django tests
      run: |
        python manage.py test
    
    - name: Check Django configuration
      run: |
        python manage.py check --deploy
    
    - name: Build Docker image
      run: |
        docker build -t pokedex-app:${{ github.sha }} .
    
    - name: Test Docker image
      run: |
        docker run -d --name pokedex-test -p 8000:8000 pokedex-app:${{ github.sha }}
        sleep 15
        curl -f http://localhost:8000/pokemon/ || exit 1
        docker stop pokedex-test
        docker rm pokedex-test
    
    - name: Clean up Docker images
      if: always()
      run: |
        docker rmi pokedex-app:${{ github.sha }} || true

